# -*- coding: utf-8 -*-
"""ml2-7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nkzEN4mVmCN5Oqpc_1qyB_Ygh5mQnQcr
"""

import pandas as pd
from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.estimators import MaximumLikelihoodEstimator
from pgmpy.inference import VariableElimination
data = pd.DataFrame([
    ['Sunny', 'Hot', 'High', 'False', 'No'],
    ['Sunny', 'Hot', 'High', 'True', 'No'],
    ['Overcast', 'Hot', 'High', 'False', 'Yes'],
    ['Rain', 'Mild', 'High', 'False', 'Yes'],
    ['Rain', 'Cool', 'Normal', 'False', 'Yes'],
    ['Rain', 'Cool', 'Normal', 'True', 'No'],
    ['Overcast', 'Cool', 'Normal', 'True', 'Yes'],
    ['Sunny', 'Mild', 'High', 'False', 'No'],
    ['Sunny', 'Cool', 'Normal', 'False', 'Yes'],
    ['Rain', 'Mild', 'Normal', 'False', 'Yes'],
    ['Sunny', 'Mild', 'Normal', 'True', 'Yes'],
    ['Overcast', 'Mild', 'High', 'True', 'Yes'],
    ['Overcast', 'Hot', 'Normal', 'False', 'Yes'],
    ['Rain', 'Mild', 'High', 'True', 'No']
], columns=['Outlook', 'Temperature', 'Humidity', 'Windy', 'Play'])

model = DiscreteBayesianNetwork([
    ('Outlook', 'Play'),
    ('Temperature', 'Play'),
    ('Humidity', 'Play'),
    ('Windy', 'Play')
])

model.fit(data, estimator=MaximumLikelihoodEstimator)
print("\nLearned CPDs:")
for cpd in model.get_cpds():
    print(cpd)
infer = VariableElimination(model)
query_result = infer.query(
    variables=['Play'],
    evidence={'Outlook': 'Sunny', 'Humidity': 'High'}
)
print("\nProbability of Play given Outlook='Sunny' and Humidity='High':")
print(query_result)