# -*- coding: utf-8 -*-
"""ml2-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eQJR0feW9Wp5084dzHRsNAofjarACzhE
"""

import pandas as pd
import Orange
from sklearn.datasets import load_iris

data = load_iris()
df = pd.DataFrame(data.data, columns=data.feature_names)
df['species'] = pd.Categorical.from_codes(data.target, data.target_names)
df.to_csv("iris.csv", index=False)

def load_dataset(csv_path):
    df = pd.read_csv(csv_path)
    attributes = []
    for col in df.columns[:-1]:
        if df[col].dtype == 'object':
            values = list(map(str, df[col].unique()))
            attributes.append(Orange.data.DiscreteVariable(col, values))
        else:
            attributes.append(Orange.data.ContinuousVariable(col))
    class_col = df.columns[-1]
    class_values = list(map(str, df[class_col].unique()))
    class_var = Orange.data.DiscreteVariable(class_col, class_values)
    domain = Orange.data.Domain(attributes, class_var)
    data_as_str = df.astype(str).values.tolist()
    table = Orange.data.Table.from_list(domain, data_as_str)
    return table
def apply_cn2_learner(table):
    learner = Orange.classification.rules.CN2Learner()
    classifier = learner(table)
    return classifier
def apply_foil_like_learner(table):
    learner = Orange.classification.rules.CN2SDUnorderedLearner()
    classifier = learner(table)
    return classifier
def display_rules(classifier):
    print("\nLearned Rules:\n")
    for rule in classifier.rule_list:
        print(rule)

def main():
    csv_path = "iris.csv"
    table = load_dataset(csv_path)

    print("=== CN2 RULES ===")
    cn2_classifier = apply_cn2_learner(table)
    display_rules(cn2_classifier)

    print("\n=== FOIL-LIKE RULES ===")
    foil_classifier = apply_foil_like_learner(table)
    display_rules(foil_classifier)

if __name__ == "__main__":
    main()