# -*- coding: utf-8 -*-
"""ml2-6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b1HIk9v_oWKDJz-p9e_ZO994eJAXSSN1
"""

import random
def generate_uniform():
    return random.uniform(0, 1)

def f(x):
    return x**2

samples = [generate_uniform() for _ in range(10)]
f_values = [f(x) for x in samples]

for i, (x, fx) in enumerate(zip(samples, f_values), 1):
    print(f"Sample {i}: x = {x:.4f}, f(x) = {fx:.4f}")

I_estimate = sum(f_values) / len(f_values)
print(f"\nEstimated integral I using Monte Carlo method: {I_estimate:.4f}")